<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;netstandard2.0;net8.0-windows</TargetFrameworks>
    <LangVersion>latest</LangVersion>
    <PlatformTarget>x86</PlatformTarget>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>NetToGXSim3.Core</RootNamespace>
    <AssemblyName>NetToGXSim3.Core</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
  </ItemGroup>

</Project>
